### ISSUE TITLE
Respect cmd key on MacOS

### ISSUE THREAD

**Issue by Deseteral** [josephernest/writing#11]
On MacOS native key shortcuts like `cmd + s` will save an html page instead of Markdown document. When user is using MacOS, application should bind different keys for shortcuts:

CMD + D: Toggle display mode
CMD + P: Print or export as PDF
CMD + S: Save source code as .MD file

etc.

**Comment by josephernest** [comment]
Very good idea! Pull request welcome if you have an idea about this (probably just a few bytes to modify in the Javascript code to accept CMD). If you can test on a Mac, thanks in advance :)

PS: I've done this in the past [around here](https://github.com/josephernest/bigpicture.js/blob/master/bigpicture.js#L255), is it `e.metaKey` for CMD?

**Comment by Deseteral** [comment]
Sure I'm definitely going to look at it 😄

**Comment by Deseteral** [comment]
Yes, it looks like `e.metaKey` is indeed a cmd key. 
`Markdown.Editor.js` was good already, so the only change is in `index.html` file :)
