### ISSUE TITLE
Support for Org syntax?

### ISSUE THREAD

**Issue by kaushalmodi** [josephernest/writing#13]
Of this request gets enough upvotes, would you consider supporting Org syntax?

Org syntax: http://orgmode.org/worg/dev/org-syntax.html

It's very similar to Markdown if using Org *just* as a markup.

**Comment by kaushalmodi** [comment]
I don't know Javascript, but I believe search/replace and regular expressions and help me add org-mode support. My attempts are here: https://github.com/kaushalmodi/writing/tree/org-mode

*So far added support for Org mode headings and inline code.*

**Comment by josephernest** [comment]
Thanks a lot!
I currently know nothing about Org, and I will have very few time in the near future to learn Org-syntax myself,  or merge Org-related pull requests.
As I want to keep this tool really short and minimalistic, let's consider [your fork](https://github.com/kaushalmodi/writing/tree/org-mode) as the most up-to-date version regarding Org! 

Thanks again!

**Comment by kaushalmodi** [comment]
Thanks for considering this as an 'official' fork.

Org mode users might want to check out https://org.scripter.co (Live site for the fork).
