### ISSUE TITLE
Bookmark files

### ISSUE THREAD

**Issue by technicaltitch** [josephernest/writing#19]
Would it be possible to bookmark files, eg, have the local file path as a URL parameter or fragment and load that file on opening? I think it'd be my default Word processor if so.

**Comment by josephernest** [comment]
This would be great indeed @technicaltitch! But, as for as I know, for security reasons, it's a big thing that Javascript has **no rights** to access the local filesystem (if it could, it would allow a malicious website to access/delete files on your computer!). So I don't think this is possible.

A solution would be to host the files in the cloud (in a transparent way for the user), like most web services do (GoogleDocs, pastebin, jsfiddle, etc.). Would you use that?

**Comment by technicaltitch** [comment]
Thanks hugely, I hadn't thought about that. Personally I want to use this offline as I live somewhere where internet access is often blocked, so something like LocalStorage, but I'm probably not a common use case.

**Comment by Steve2955** [comment]
@josephernest @technicaltitch Another solution to this problem(and that's also something I thought about already) is 'porting' the whole project over to Electron. Of course it would be less lightweight but you can gain access to the filesystem and a whole lot else.

**Comment by technicaltitch** [comment]
I wouldn't personally second that - part of the reason I like this project so much is it's simplicity - been using VS Code and don't like the CPU churn, my browser's open 24x7 anyway.

**Comment by josephernest** [comment]
Indeed Electron could be a solution for a standalone version of Writing, but there's maybe already hundreds of standalone markdown editors, so I don't know if it's worth porting it?

I close this issue for now, as there's no real solution to access the local filesystem with JS.
