### ISSUE TITLE
Fake bold/italic font styles

### ISSUE THREAD

**Issue by johannschopplich** [josephernest/writing#21]
Using asterisks or rather the bold/italic markdown syntax results in fake displayed fonts, because the real font styles are missing. 

![screenshot-2017-10-23 writing](https://user-images.githubusercontent.com/27850750/31905247-d6c58e56-b82d-11e7-8c70-663caea38c91.png)

I recommend implementing the missing styles like this:

```
@font-face {
  font-family: ComputerModern;
  src: url('ComputerModern-Regular.otf') format('otf');
  font-weight: 400;
  font-style: normal;
  font-stretch: normal;
}
@font-face {
  font-family: ComputerModern;
  src: url('ComputerModern-RegularItalic.otf') format('otf');
  font-weight: 400;
  font-style: italic;
  font-stretch: normal;
}
@font-face {
  font-family: ComputerModern;
  src: url('ComputerModern-Bold.otf') format('otf');
  font-weight: 700;
  font-style: normal;
  font-stretch: normal;
}
@font-face {
  font-family: ComputerModern;
  src: url('ComputerModern-BoldItalic.otf') format('otf');
  font-weight: 700;
  font-style: italic;
  font-stretch: normal;
}
```

**Comment by josephernest** [comment]
Thanks! Can you provide a live demo of your fork implementing these changes?
What is the source for these files/is their license ok for using it here?

**Comment by josephernest** [comment]
Re @jschopplich I'm very interested. Could you do a pull request with the relevant files?
I used `cmunrm.otf` and this source: http://cm-unicode.sourceforge.net/

**Comment by johannschopplich** [comment]
I created a pull request the day you asked for one. 😄 I just didn't know how to link it to this issue:

Here it is: https://github.com/josephernest/writing/pull/23

**Comment by josephernest** [comment]
Ohhh my bad, I didn't see it, so sorry @jschopplich ! 
I implemented bold in the meantime, between our 2 messages. I'll see if I can merge.

**Comment by johannschopplich** [comment]
I initially thought there was no interest no more, but now I'm proven wrong! So I'm glad, too, @josephernest .

Yes, I saw your recent commit. But your implementation of just adding styles for tags isn't the right way to go. It's better to add the correct `font-face`; no need for adding styles for e.g. `strong`.
`font-weight: 700;` takes care of that. 700 is just the short version for bold.

I suggest either you revert your commit (because of the merge conflicts) or I update my pull request. The first suggestion should be faster/easier. Then you can also merge my 2nd pull request: https://github.com/josephernest/writing/pull/24 which would be great.

**Comment by josephernest** [comment]
I  added your suggestion in my the last commit.

Remark: I didn't use cmunbx.otf, as you suggested, because this seems to be Serif Bold **Extended** Roman, and I think we don't need extended here.
Also cmunti.otf doesn't seem to be exactly the same Roman font as the non-italic one (see the lowercase g in both fonts), that's why I didn't include it for now. More generally, I don't understand the naming convention `cmun*.otf`, and I didn't find exactly a CMU Serif Roman Italic.

PS: where did you find ComputerModern-RegularItalic.otf, ComputerModern-Regular.otf, as you suggested in your first post in this issue? Maybe this would be a better source for these fonts?

**Comment by johannschopplich** [comment]
Thanks for pushing the code.

As for Computer Modern's naming scheme, I don't understand them either. The original as well as official source is: [https://sourceforge.net/projects/cm-unicode/](https://sourceforge.net/projects/cm-unicode/). I just renamed both italic and bold styles to `ComputerModern-RegularItalic.otf` and `ComputerModern-Regular.otf` respectively for clarity.
That's right. Nevertheless it seemes _Serif Bold Extended Roman_ actually is used as bold style. Also there was no other bold font fitting close to the normal one. I couldn't find any information on that topic in the WWW. But comparing both fonts with some TeX-parsed documents it seemes those are the right picks.
