### ISSUE TITLE
Screen flickering bug

### ISSUE THREAD

**Issue by chaoxu** [josephernest/writing#3]
Consider the following input. I cannot find a smaller input.
No matter what you add afterward, it is going to flicker the last mathjax element. 

```
---
title: Small $L_1$ norm solution to a linear Diophantine equation 
tags: number theory
---

Let $a=(a_1,\ldots,a_n)$ be $n$ integers with $\gcd(a_1,\ldots,a_n)=1$. There exist a integral vector $x=(x_1,\ldots,x_n)$, such that $\sum_{i=1}^n x_ia_i = 1$. How large is the solution $x$? By [Bézout's lemma](https://en.wikipedia.org/wiki/Bézout%27s_identity), when $n=2$, we can obtain that $\|x\|\leq \|a\|$. Here $\|\cdot \|$ is the $L_1$ norm. 
```

**Comment by josephernest** [comment]
In fact Writing uses exactly the same rendering as the one here: https://math.stackexchange.com/questions/ask

I tested there, and the flickering is also there (Math StackExchange), sadly. So  maybe it's a good idea to post the issue on the github of Pagedown, Pagedown Extra, MathJax, or StackOverflow's editor code.
