### ISSUE TITLE
local images are not loaded in preview

### ISSUE THREAD

**Issue by hornsong** [josephernest/writing#30]
A local image ![testimage](localimage.jpg) is not loaded into the preview window. A web image with ![testimage](http:// ...) works fine in preview.

**Comment by josephernest** [comment]
This is normal, you cannot access an image from local filesystem from a http://... or https://... website, for security reasons.

Imagine what would happen if we could access to a file `file:///C:/Documents/HornsongPersonalNotes.txt` from any http:// website!

**Comment by hornsong** [comment]
Dear Joseph,

If I would have tried to access a local image from a http://   website than you are right.
But I tried to access a local image from the same local directory where your index.html file is. I browse the local index.html file in the latest Firefox browser.

Kind regards,
Lydia

Van: josephernest
Verzonden: dinsdag 31 maart 2020 14:57
Aan: josephernest/writing
CC: hornsong; Author
Onderwerp: Re: [josephernest/writing] local images are not loaded in preview(#30)

This is normal, you cannot access an image from local filesystem from a http://... or https://... website.
Imagine what would happen if we could access to file file:///C:/Documents/HornsongPersonalNotes.csv from any http:// website...
