### ISSUE TITLE
Support dark mode?

### ISSUE THREAD

**Issue by deepakjois** [josephernest/writing#4]
I would love to use this in dark mode. Hope it is not very difficult to implement. A possible implementation could be to have a keyboard shortcut to flip the viewing mode.

**Comment by josephernest** [comment]
I'm very short of time these days to add such things, but feel free to fork it and send a link and I'll test it.

**Comment by Steve2955** [comment]
I added a dark mode to my fork. You can check it out [here](https://steve2955.github.io/writing/index.html).

And this is the first time I am contributing to an open-source project, so I would really appreciate some advice.

Edit: pull request #15
